import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const poppins = Poppins({
   weight: ["300", "400", "500", "600", "700"],
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Master.TI",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="pt-BR" className="scroll-smooth">
         <body className={poppins.className}>
            <div className="flex-1">{children}</div>
            <Footer />
         </body>
      </html>
   );
}
